<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<testsuite failures="1" name="cucumber.runtime.formatter.JUnitFormatter" skipped="0" tests="3" time="34.017918">
<testcase classname="PostRefundTest" name="Validate the Response Data of For Post valid uuid for refund" time="3.839799">
<system-out><![CDATA[When user post refund with valid uuid.......................................passed
Then verify statusCode as 201...............................................passed
]]></system-out>
</testcase>
<testcase classname="PostRefundTest" name="Validate the Response Data of For Post invalid uuid for refund" time="0.01651">
<system-out><![CDATA[When user post refund with uuid "test"......................................passed
Then verify statusCode as 400...............................................passed
]]></system-out>
</testcase>
<testcase classname="PostRefundTest" name="Validate the Response Data of For Post same uuid for refund concurrent" time="30.161609">
<failure message="java.lang.AssertionError: expected [true] but found [false]&#10;&#9;at org.testng.Assert.fail(Assert.java:97)&#10;&#9;at org.testng.Assert.failNotEquals(Assert.java:969)&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:43)&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:53)&#10;&#9;at StepFiles.PostRefundSteps.userPostRefundWithUuidInParallel(PostRefundSteps.java:46)&#10;&#9;at ✽.When user post refund with uuid in parallel(PostRefundTest.feature:12)&#10;"><![CDATA[When user post refund with uuid in parallel.................................failed
Then verify statusCode as 423...............................................skipped

StackTrace:
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:97)
	at org.testng.Assert.failNotEquals(Assert.java:969)
	at org.testng.Assert.assertTrue(Assert.java:43)
	at org.testng.Assert.assertTrue(Assert.java:53)
	at StepFiles.PostRefundSteps.userPostRefundWithUuidInParallel(PostRefundSteps.java:46)
	at ✽.When user post refund with uuid in parallel(PostRefundTest.feature:12)
]]></failure>
</testcase>
</testsuite>
